### ISSUE TITLE
Replacement Integrated Tileset

### ISSUE THREAD

**Issue by VaneFox** [Kenan2000/CDDA-Kenan-Modpack#159]
Apologies if this isn't the best place to talk about this.
However with the removal of UDP and the questionable reasons behind it, it might have problems down the line for this pack's built-in function.

I think MShockXotto is quite complete and would fit well as a replacement, and if anything, I'm looking to put in some art to fill blanks if help is required.

**Comment by Kenan2000** [comment]
@VaneFox Well, no need to apologize, because this is a right place for having discussions :-) 

Let me explain this, thanks to work of @Theawesomeboophis along with him making this pull request https://github.com/Kenan2000/CDDA-Kenan-Modpack/pull/153, `mod_tileset.json` files incorporated into mods in my Modpacks have support both for UDP tileset, MShockXotto, MXotto+, ChibiUltica, other tilesets which support such format, whether official or unofficial, third party, community tilesets, both types can have support for tiles, so you can see that tiles in mods in my Modpacks support all of these tilesets

Another thing which I would like to kindly explain, I really hope that you're not implying getting rid of UDP tileset support in mods, because this is something that is strictly prohibited, majority of tiles made for mods here are thanks to SDG's work, creator of UDP tileset, this is why support for his tileset is mandatory, because it would be neglecting a work of such a valuable author, without work of which none of these tiles would exist at all 

Along with this, UDP tileset is continued to be maintained thanks to work of @SzQ1, Bright Nights fork developers

**Comment by Theawesomeboophis** [comment]
I'm also going to try my best to maintain it on dda side, it is very much not obsolete, and there are hundreds of forks of the last version floating around as well.

**Comment by SzQ1** [comment]
`thanks to work of @SzQ1, Bright Nights fork developers` 
I did nearly nothing for UDP so far 👍

**Comment by Kenan2000** [comment]
> I'm also going to try my best to maintain it on dda side, it is very much not obsolete, and there are hundreds of forks of the last version floating around as well.

@Theawesomeboophis Look at updated Modpacks tileset sections, hopefully you'll like this update

**Comment by Theawesomeboophis** [comment]
Thanks, I'll try to get an update up this weekend, having some spriting issues that need to be fixed before update is added though.
