### ISSUE TITLE
Arcana mod_tileset issue

### ISSUE THREAD

**Issue by chrispikula** [Kenan2000/CDDA-Kenan-Modpack#50]
Hello!
So, I use the undead people (new version) tileset, and ran into an issue with Arcana.

The "compatibility" error showed up for each mod_tileset in \Arcana\mod_tileset\mod_tileset.json that didn't have an undead people option.  This was easy enough to figure out.  Just delete the entries on my local copy.  No worries, yeah?

Then I ran into 
Invalid or misplaced field name "overlay_ordering" in JSON data

Turns out, the 
{
"type": "overlay_order", 
"overlay_ordering": [
...
block should be at the bottom of the file, not the top.

Not sure who I should mention this to, as in the Arcana repository, the mod_tileset folder is only in the bright nights version.  In this repository, it isn't.

Hope this helps someone else googling for the information someday in the future.

**Comment by Kenan2000** [comment]
@chrispikula This along with the compatibility one is a permanent issue that may or may not get fixed by the developers, don't worry about it, it is absolutely harmless and can be skipped by pressing `i` or `Shift+i`, I am not planning to fix it in the meantime because the problem here lies in the way game accepts JSON - despite the JSON being perfectly correct - it is something that developers might take a look into sometime in the future when tinkering with C++ code of the game
