### ISSUE TITLE
Misc error messages

### ISSUE THREAD

**Issue by meelock** [Kenan2000/CDDA-Kenan-Modpack#6]
```
 DEBUG    : itype 'mutagen_tortoise' uses undefined flag 'MUTAGEN_TORTOISE'. Please add corresponding 'json_flag' entry to json.

 FUNCTION : Item_factory::finalize_post(itype&)::<lambda(const flag_id&)>
 FILE     : src/item_factory.cpp
 LINE     : 501 
```

```
 DEBUG    : Monster type 'dks_mon_lurker_sewer' has invalid default_faction: 'lurker'. Add this faction to json as MONSTER_FACTION type.

 FUNCTION : void MonsterGenerator::finalize_mtypes()
 FILE     : src/monstergenerator.cpp
 LINE     : 373
```

```
 DEBUG    : Tried to set invalid ammo of battery for shockcannon_ups

 FUNCTION : item& item::ammo_set(const itype_id&, int)
 FILE     : src/item.cpp
 LINE     : 554
```

```
 DEBUG    : warnings for type dks_mon_flamesword:
uses no skill


 FUNCTION : void Item_factory::check_definitions() const
 FILE     : src/item_factory.cpp
 LINE     : 1477
```
```

 DEBUG    : tried to put an item (cabbage) count (9) in a container (bowl_plastic) that cannot contain it: pocket unacceptable because item is too heavy

 FUNCTION : ret_val<bool> item::put_in(const item&, item_pocket::pocket_type)
 FILE     : src/item.cpp
 LINE     : 1053
```
```

 DEBUG    : Mapgen BL9_anomaly_cultden1 is not used by anything!

 FUNCTION : void mapgen_factory::check_consistency()
 FILE     : src/mapgen.cpp
 LINE     : 331
```

```
 DEBUG    : both into and into_group defined for monster mon_coyote_wolf

 FUNCTION : void MonsterGenerator::check_monster_definitions() const
 FILE     : src/monstergenerator.cpp
 LINE     : 1268
```
```

 DEBUG    : monster mon_rat_mole_lesser is flagged milkable, but has no starting ammo

 FUNCTION : void MonsterGenerator::check_monster_definitions() const
 FILE     : src/monstergenerator.cpp
 LINE     : 1184
```

```
 DEBUG    : monster mon_tame_large_acid_ant_larva has invalid harvest_entry: meat_slug

 FUNCTION : void MonsterGenerator::check_monster_definitions() const
 FILE     : src/monstergenerator.cpp
 LINE     : 1229
```

```
 DEBUG    : tried to put an item (diesel, amount 1) in a container (55gal_drum) that cannot contain it

 FUNCTION : int item::fill_with(const item&, int)
 FILE     : src/item.cpp
 LINE     : 8777

```

World Download:
[Toco.zip](https://github.com/Kenan2000/CDDA-Kenan-Modpack/files/5611035/Toco.zip)

**Comment by Kenan2000** [comment]
Fixed most of the errors in the most recent commit, now what's left:

BL9 `not used by anything` errors are deliberate - it is WIP and this is some of the untouched stuff that is being worked on - soon these locations WILL be used and properly utilized, when the big amazing update arrives, it will take some time though :-) 

Not really sure how to fix the `diesel in a 55gal_drum` one, have not encountered it myself and searching `55gal_drum` in modpack files via extensive Notepad++ search functions yielded no results

`Into and into_group` error is tricky - honestly, no idea how to fix it right now especially considering that it absolutely does not affect gameplay - fixing this can wait, I believe

All the other errors have been fixed in the most recent commit https://github.com/Kenan2000/CDDA-Kenan-Modpack/commit/366b18d2e0f73b200a832e4f02e3933a9562fde2 , most, if not all :-)

**Comment by Kenan2000** [comment]
Ah and of course, thank you, @meelock for posting about these errors, I truly appreciate help provided, this modpack exists only because people like you and many, many, many others post about errors - without your, guys, help, this would not be possible at all - maintaining this modpack with as little errors as possible :-)
