### ISSUE TITLE
Duplicate Professions

### ISSUE THREAD

**Issue by Ichthysdekilt** [Kenan2000/CDDA-Kenan-Modpack#61]
I just confirmed with a new install, but I'm still getting the following error on load and character creation:

<img width="489" alt="Screenshot 2021-04-01 202651" src="https://user-images.githubusercontent.com/63475824/113367607-6f4a9380-932a-11eb-8c30-cd7f1508ede6.png">

[mods.json.txt](https://github.com/Kenan2000/CDDA-Kenan-Modpack/files/6247065/mods.json.txt)

**Comment by Kenan2000** [comment]
@Ichthysdekilt I actually would like to keep this one, it's harmless and well, is a good indication that there is always work to do and maintain in the Modpack, I just don't like the idea of making everything 100% perfect, if you know what I mean, because there is always work, always something breaks with updates, you know :p

**Comment by Ichthysdekilt** [comment]
@Kenan2000 Thanks anyway!  I really appreciate everything you do with this mod pack!
