### ISSUE TITLE
New Secronom Issues

### ISSUE THREAD

**Issue by Ichthysdekilt** [Kenan2000/CDDA-Kenan-Modpack#72]
Loaded up the latest modpack, 966fc5a, added Sec+, and ran into these new secronom issues.

<img width="962" alt="Secronom+ Circular Dependency" src="https://user-images.githubusercontent.com/63475824/115152070-a5cc2200-a03d-11eb-8456-2b2a93f6fe65.png">
<img width="419" alt="Saddler Cave Not Used" src="https://user-images.githubusercontent.com/63475824/115152068-a5cc2200-a03d-11eb-9188-5d893f2e1d32.png">
<img width="501" alt="Secronom Profession Duplication" src="https://user-images.githubusercontent.com/63475824/115152069-a5cc2200-a03d-11eb-9e6d-0fb4a9344672.png">

I'm on 11581 Win64 with the following mods (can also provide a save zip if it helps!) and the latest UP Tiles:
[mods.txt](https://github.com/Kenan2000/CDDA-Kenan-Modpack/files/6331648/mods.txt)

**Comment by linonetwo** [comment]
duplicate profession is fixed by bertdong.

I don't have problem 1 and 2 in latest modpack and b11572, maybe check is introduced in latest release?

**Comment by Kenan2000** [comment]
@Ichthysdekilt Well, I cannot really replicate these errors that you're posting with either just Secronom or both Secronom and the Secronom lore expansion enabled at the same time, now I'm not responsible for maintaining Graphical Overmap Secronom Addon, SDG is, since he's the author of it as well, it's not in any of my Modpacks so SDG may be able to fix it once he has some time to spare pretty much

**Comment by Ichthysdekilt** [comment]
@Kenan2000 oh, I'm sorry -  I didn't realize it was coming from there.  Thank you for looking into it!
